"""Added updated_by, updated_date to categories

Revision ID: 1f105067887a
Revises: 1d2d9d25b688
Create Date: 2025-04-04 11:40:22.773637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f105067887a'
down_revision: Union[str, None] = '1d2d9d25b688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'updated_date')
    op.drop_column('categories', 'updated_by')
    # ### end Alembic commands ###
