"""Added updated_by and updated_date to mcq

Revision ID: 20a24e706c77
Revises: 75ad9d29c37f
Create Date: 2025-04-02 17:20:35.349041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a24e706c77'
down_revision: Union[str, None] = '75ad9d29c37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcq', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('mcq', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'mcq', 'roles', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcq', type_='foreignkey')
    op.drop_column('mcq', 'updated_date')
    op.drop_column('mcq', 'updated_by')
    # ### end Alembic commands ###
